### ISSUE TITLE
BBI: covariate estimator currently only supports `sampling_RF` and `RF`

### ISSUE THREAD

**Issue by jpaillard** [mind-inria/hidimstat#13]
https://github.com/mind-inria/hidimstat/blob/7c3af80e501e2c448dd7b1dbf21f1159c17c514b/hidimstat/compute_importance.py#L231-L434

The implementation of `compute_importance` only supports two covariate estimators (`sampling_RF` and `RF`). Any other estimator would lead to an error when calling `hypertune_predictor` which uses hyper-parameters specific to forests. 

Maybe we could allow for more flexibility, for instance using linear models to predict covariates.

**Comment by bthirion** [comment]
This is a valid point ! I would include RidgeCV as an alternative.

**Comment by jpaillard** [comment]
Closing since it has been addressed in #14
