### ISSUE TITLE
Missing doc for CPI & LOCO

### ISSUE THREAD

**Issue by jpaillard** [mind-inria/hidimstat#19]
I forgot to update the `doc_conf` in #14 resulting in the documentation of the new estimators not showing up on the website. 
https://github.com/mind-inria/hidimstat/blob/fe4836fa2e2b501b46455cc9d1d0695a849662dd/doc_conf/api.rst?plain=1#L20C1-L20C24

**Comment by bthirion** [comment]
Indeed. Can you work on it ? Thx,
