### ISSUE TITLE
CPI: more fine-grained control of predict methods

### ISSUE THREAD

**Issue by dengemann** [mind-inria/hidimstat#26]
I think we should allow for an API like ```CPI(score_method='predict_proba')``` and add support for e.g. ```CPI(score_method='decision_function')``` to support non-probabilistic models, e.g. SVM or RidgeClassifier. Any thoughts @bthirion @jpaillard ?

**Comment by bthirion** [comment]
Why not, but this means that we have to check systematically that this yields reasonable outputs (it is probably the case, but we have not checked so far)

**Comment by jpaillard** [comment]
For me that would make sense to support more classification methods, like LDA, RidgeClassifier ... for which it makes more sense to compute the NLL on the decision function than the predicted class. 

We could have something like `getattr(self.estimator, self.method)(X)` alongside a `check_method` function. 

I can work on an example to check that the results are reasonable.

**Comment by bthirion** [comment]
I really like the idea to start with an example !
