### ISSUE TITLE
Accelerate CPI by using batch prediction and Numpy array operations instead of for loop

### ISSUE THREAD

**Issue by jpaillard** [mind-inria/hidimstat#30]
I think that the loop over permutations in the `CPI.predict` function could be avoided by creating larger arrays, predicting over a batch and reshaping the output. 

Old version: 
-------------
```python
for _ in range(B):
   X_permuted.shape = NxP
   y_pred_list.append(model.predict(X_permuted))
y_pred_perm = np.array(y_pred_list)
y_pred_perm.shape = B x N
```

New version:
-------------
```python
X_permuted_all.shape = NBxP
y_pred_perm = model.predict(X_permuted_all)
y_pred_perm.reshape(B, N, )
```

Running a benchmark on my laptop for n_permutations = 100 leads to 30% faster. 
![image](https://github.com/user-attachments/assets/d842fba6-3007-4db2-b7cc-dd5c141c92b0)

**Comment by bthirion** [comment]
A decent win indeed ! I guess that the arrays are small enough that having a big one does not harm performance.
