### ISSUE TITLE
Separate folder for side function?

### ISSUE THREAD

**Issue by lionelkusch** [mind-inria/hidimstat#93]
Based on the issue https://github.com/mind-inria/hidimstat/issues/86 :
> That could avoid having the 'extra' folder, which is not so straightforward. Instead, we have 'datasets' and 'stat_tools.'

**Comment by lionelkusch** [comment]
> I think it would be good to keep toy_datasets and stat_tools separate as they don't seem to be related and also rename to datasets and stats.

**Comment by lionelkusch** [comment]
> I would not have too many levels. extra/toy_data and extra/stat_tools should rather be something like a utils module. (extra is not a good name I'm afraid).

**Comment by lionelkusch** [comment]
> I didn't add them to _utils because there are functions required, for example and tests. They shouldn't be private functions. We need to make a difference between side functions, which are public and side functions, which are private.

**Comment by lionelkusch** [comment]
@jpaillard @man-shu @bthirion

I am not really a fan of adding the folder 'datasets' and 'stat_tools' directly to the main package. I prefer to keep them in a subfolder.
I understand that the term 'extra' is not a good choice. Do you think that 'utils' is better ?

I realise that there will be at least three files to avoid having _utils function in tests and examples:
- dataset
- stat
- visualisation

**Comment by bthirion** [comment]
But datasets and stat_tools are really two different things, so I don't understand the advantage of having them together. Did I misunderstand your intent ?

**Comment by lionelkusch** [comment]
I want “ side functions ” to be separated from the core library. 
However, this doesn't seem to be the case for scikit-learn and nilearn. I can use their approach instead if you think this separation is not useful.

**Comment by bthirion** [comment]
From a use standpoint, I'm not sure you gain anything with the separation ?

**Comment by lionelkusch** [comment]
ok

**Comment by lionelkusch** [comment]
We won't use a specific folder for side functions.
